src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 */
class Property {
    
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct() {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getTitle(): ?string {
        return $this->title;
    }

    public function setTitle(string $title): self {
        $this->title = $title;

        return $this;
    }
    
    public function getSlug(): string {
        return (new Slugify)->slugify($this->title);
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(?string $description): self {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int {
        return $this->surface;
    }

    public function setSurface(int $surface): self {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int {
        return $this->floor;
    }

    public function setFloor(int $floor): self {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int {
        return $this->price;
    }

    public function setPrice(int $price): self {
        $this->price = $price;

        return $this;
    }
    
    public function getFormattedPrice(): string {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int {
        return $this->heat;
    }

    public function setHeat(int $heat): self {
        $this->heat = $heat;

        return $this;
    }
    
    public function getHeatType() :string {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string {
        return $this->city;
    }

    public function setCity(string $city): self {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string {
        return $this->address;
    }

    public function setAddress(string $address): self {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool {
        return $this->sold;
    }

    public function setSold(bool $sold): self {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self {
        $this->created_at = $created_at;

        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices() {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }

}

src/Controller/PropertyController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Description of PropertyController
 *
 * @author barnabas
 */
class PropertyController extends AbstractController {

    private $repository;
    private $em;

    public function __construct(PropertyRepository $repository, ObjectManager $em) {
        $this->repository = $repository;
        $this->em = $em;
    }

    public function index(PaginatorInterface $paginator, Request $request): Response {

        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
                $this->repository->findAllVisibleQuery($search),
                $request->query->getInt('page', 1),
                12
        );
        return $this->render('property/index.html.twig', [
                    'properties' => $properties,
                    'form' => $form->createView()
        ]);
    }

    public function show(Property $property, string $slug): Response {

        if ($property->getSlug() !== $slug) {
            return $this->redirectToRoute('property.show', [
                        'id' => $property->getId(),
                        'slug' => $property->getSlug()
                            ], 301);
        }

        return $this->render('property/show.html.twig', [
                    'property' => $property
        ]);
    }

}

templates/property/index.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <!-- banner -->
    <div class="inside-banner">
        <div class="container"> 
            <span class="pull-right"><a href="{{ path('home') }}">Home</a> / Buy, Sale & Rent</span>
            <h2>Buy, Sale & Rent</h2>
        </div>
    </div>
    <!-- banner -->


    <div class="container">
        <div class="properties-listing spacer">

            <div class="row">
                <div class="col-lg-3 col-sm-4 ">

                    <div class="search-form">
                        <h4>
                            <span class="glyphicon glyphicon-search"></span> Search for
                        </h4>
                        {{ form_start(form) }}
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form_row(form.minSurface) }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form_row(form.maxPrice) }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    {{ form_row(form.city) }}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Find Now</button>
                            {{ form_rest(form) }}
                        {{ form_end(form) }}
                    </div>



                    <div class="hot-properties hidden-xs">
                        <h4>Hot Properties</h4>
                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/1.jpg" class="img-responsive img-circle" alt="properties"></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/1.jpg" class="img-responsive img-circle" alt="properties"></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/1.jpg" class="img-responsive img-circle" alt="properties"></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/1.jpg" class="img-responsive img-circle" alt="properties"></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                    </div>


                </div>

                <div class="col-lg-9 col-sm-8">
                    <div class="sortby clearfix">
                        <div class="pull-left result">Showing: 12 of 100 </div>
                        <div class="pull-right">
                            <select class="form-control">
                                <option>Sort by</option>
                                <option>Price: Low to High</option>
                                <option>Price: High to Low</option>
                            </select></div>

                    </div>
                    <div class="row">

                        <div class="row">
                            {% for property in properties %}
                                <!-- properties -->
                                <div class="col-lg-4 col-sm-6">
                                    <div class="properties">
                                        <div class="image-holder"><img src="/front/images/properties/1.jpg" class="img-responsive" alt="properties">
                                            <div class="status sold">Sold</div>
                                        </div>
                                        <h4><a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a></h4>
                                        <p class="price">Price: ${{ property.FormattedPrice }}</p>
                                        <div class="listing-detail">
                                            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Rooms">{{ property.rooms }}</span> 
                                            <span data-toggle="tooltip" data-placement="bottom" data-original-title="BedRooms">{{ property.bedrooms }}</span> 
                                            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Surface">{{ property.surface }}</span> 
                                            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Floor">{{ property.floor }}</span> 
                                        </div>
                                        <a class="btn btn-primary" href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">View Details</a>
                                    </div>
                                </div>
                                <!-- properties -->
                            {% endfor %}
                        </div>

                        <div class="row">
                            <div class="center">
                                <div class="pagination">
                                    {{ knp_pagination_render(properties) }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <!-- banner -->
    <div class="inside-banner">
        <div class="container"> 
            <span class="pull-right"><a href="{{ path('home') }}">Home</a> / Buy</span>
            <h2>Buy</h2>
        </div>
    </div>
    <!-- banner -->


    <div class="container">
        <div class="properties-listing spacer">

            <div class="row">
                <div class="col-lg-3 col-sm-4 hidden-xs">

                    <div class="hot-properties hidden-xs">
                        <h4>Hot Properties</h4>
                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/4.jpg" class="img-responsive img-circle" alt="properties"/></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/1.jpg" class="img-responsive img-circle" alt="properties"/></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/3.jpg" class="img-responsive img-circle" alt="properties"/></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-4 col-sm-5"><img src="/front/images/properties/2.jpg" class="img-responsive img-circle" alt="properties"/></div>
                            <div class="col-lg-8 col-sm-7">
                                <h5><a href="property-detail.php">Integer sed porta quam</a></h5>
                                <p class="price">$300,000</p> </div>
                        </div>

                    </div>



                    <div class="advertisement">
                        <h4>Advertisements</h4>
                        <img src="/front/images/advertisements.jpg" class="img-responsive" alt="advertisement">

                    </div>

                </div>

                <div class="col-lg-9 col-sm-8 ">

                    <h2>{{ property.rooms }} room and {{ property.bedrooms }} bedrooms apartment</h2>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="property-images">
                                <!-- Slider Starts -->
                                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                                    <!-- Indicators -->
                                    <ol class="carousel-indicators hidden-xs">
                                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                                        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
                                        <li data-target="#myCarousel" data-slide-to="3" class=""></li>
                                    </ol>
                                    <div class="carousel-inner">
                                        <!-- Item 1 -->
                                        <div class="item active">
                                            <img src="/front/images/properties/4.jpg" class="properties" alt="properties" />
                                        </div>
                                        <!-- #Item 1 -->

                                        <!-- Item 2 -->
                                        <div class="item">
                                            <img src="/front/images/properties/2.jpg" class="properties" alt="properties" />

                                        </div>
                                        <!-- #Item 2 -->

                                        <!-- Item 3 -->
                                        <div class="item">
                                            <img src="/front/images/properties/1.jpg" class="properties" alt="properties" />
                                        </div>
                                        <!-- #Item 3 -->

                                        <!-- Item 4 -->
                                        <div class="item ">
                                            <img src="/front/images/properties/3.jpg" class="properties" alt="properties" />

                                        </div>
                                        <!-- # Item 4 -->
                                    </div>
                                    <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                                    <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                                </div>
                                <!-- #Slider Ends -->

                            </div>




                            <div class="spacer"><h4><span class="glyphicon glyphicon-th-list"></span> Properties Detail</h4>
                                {{ property.description }}
                            </div>
                            <div><h4><span class="glyphicon glyphicon-map-marker"></span> Location</h4>
                                <div class="well">
                                    <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Pulchowk,+Patan,+Central+Region,+Nepal&amp;aq=0&amp;oq=pulch&amp;sll=37.0625,-95.677068&amp;sspn=39.371738,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Pulchowk,+Patan+Dhoka,+Patan,+Bagmati,+Central+Region,+Nepal&amp;ll=27.678236,85.316853&amp;spn=0.001347,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe></div>
                            </div>

                        </div>
                        <div class="col-lg-4">
                            <div class="col-lg-12  col-sm-6">
                                <div class="property-info">
                                    <p class="price">$ {{ property.formattedPrice }}</p>
                                    <p class="area"><span class="glyphicon glyphicon-map-marker"></span> {{ property.postalCode }}, {{ property.address }}</p>

                                    <div class="profile">
                                        <span class="glyphicon glyphicon-user"></span> Agent Details
                                        <p>John Parker<br>009 229 2929</p>
                                    </div>
                                </div>

                                <h6><span class="glyphicon glyphicon-home"></span> Availabilty</h6>
                                <div class="listing-detail">
                                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Rooms">{{ property.rooms }}</span> 
                                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="BedRooms">{{ property.bedrooms }}</span> 
                                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Surface">{{ property.surface }}</span> 
                                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Floor">{{ property.floor }}</span> 
                                </div>

                            </div>
                            <div class="col-lg-12 col-sm-6 ">
                                <div class="enquiry">
                                    <h6><span class="glyphicon glyphicon-envelope"></span> Post Enquiry</h6>
                                    <form role="form">
                                        <input type="text" class="form-control" placeholder="Full Name"/>
                                        <input type="text" class="form-control" placeholder="you@yourdomain.com"/>
                                        <input type="text" class="form-control" placeholder="your number"/>
                                        <textarea rows="6" class="form-control" placeholder="Whats on your mind?"></textarea>
                                        <button type="submit" class="btn btn-primary" name="Submit">Send Message</button>
                                    </form>
                                </div>         
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}